
static const char* get_error_info(short ret) {
	switch(ret) {
		case EW_PROTOCOL: return "protocol error"; break;
		case EW_SOCKET: return "Windows socket error"; break;
		case EW_NODLL: return "DLL not exist error"; break;
		case EW_INIERR: return "error in APi library inital valiefile"; break;
		case EW_ITLOW: return "low temperature alarm of intelligent terminal"; break;
		case EW_ITHIGHT: return "hight temperature alarm of intelligent terminal"; break;
		case EW_BUS: return "bus error"; break;
		case EW_SYSTEM2: return "system error"; break;
		case EW_HSSB: return "hssb communication error"; break;
		case EW_HANDLE: return "Windows library handle error"; break;
		case EW_VERSION: return "CNC/PMC version missmatch"; break;
		case EW_UNEXP: return"abnormal error"; break;
		case EW_SYSTEM: return "system error"; break;
		case EW_PARITY: return "shared RAM parity error"; break;
		case EW_MMCSYS: return "emm386 or mmcsys install error"; break;
		case EW_RESET: return "reset or stop occured error"; break;
		case EW_BUSY: return "busy error"; break;
		case EW_OK: return "no problem"; break;
		//case EW_FUNC: return "command prepare error"; break;
		case EW_NOPMC: return "pmc not exist"; break;
		case EW_LENGTH: return "data block length error"; break;
		//case EW_NUMBER: return "data number error"; break;
		case EW_RANGE: return "address range error"; break;
		//case EW_ATTRIB: return "data attribute error"; break;
		case EW_TYPE: return "data type error"; break;
		case EW_DATA: return "data error"; break;
		case EW_NOOPT: return "no option error"; break;
		case EW_PROT: return "write protect error"; break;
		case EW_OVRFLOW: return "memory overflow error"; break;
		case EW_PARAM: return "cnc parameter not correct error"; break;
		case EW_BUFFER: return "buffer error"; break;
		case EW_PATH: return "path error"; break;
		case EW_MODE: return "cnc mode error"; break;
		case EW_REJECT: return "execution rejected error"; break;
		case EW_DTSRVR: return "data server error"; break;
		case EW_ALARM: return "alarm has been occurred"; break;
		case EW_STOP: return "CNC is not running"; break;
		case EW_PASSWD: return "protection data error"; break;
		case EW_PMC: return "error generated by PMC"; break;
		case EW_PMCHANDLE: return "PMC handle error"; break;
		case EW_RD_OVWSTP: return "overwrite stop in program read "; break;
		case EW_RD_RSTFIN: return "reset interrupt in program read "; break;
		default: return "Unknown Error"; break;
	}
}
